name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *"
  push:
    branches:
      - "main"

jobs:
  readme-scribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: muesli/readme-scribe@d2f6ab32d6b9f5b59941fe782d6c7e6499a37fe4
        with:
          template: templates/README.md.tpl
          writeTo: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0
        with:
          commit_message: "Update generated README"
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
